---
title: Project 1 Data Analysis Plan
author: Diana Felipe
output: 
  bookdown::pdf_document2:
    toc: false
    number_sections: false
    latex_engine: xelatex
    extra_dependencies: ["longtable", "float"]
mainfont: Arial
fontsize: 12pt
documentclass: article
geometry: margin=1in
header-includes:
  - \usepackage{setspace}
  - \doublespacing
  - \usepackage{float}
  - \usepackage{caption}
  - \usepackage{titling}
  - \setlength{\droptitle}{-4cm}
  - \preauthor{\vspace{-0.6cm}}
  - \postauthor{\vspace{-3cm}}
---

```{r, echo = F, warning=F, message = F}
knitr::opts_chunk$set(echo = TRUE)


library(readr)
library(knitr)
library(ggplot2)
library(MASS)
library(emmeans)
library(multcomp)
library(kableExtra)
library(stats)
library(dplyr)
library(tibble)
library(labelled)
library(tableone)
library(lme4)
library(lmerTest)
library(nlme)
library(gtsummary)
library(gt)
library(ggeffects)
library(UpSetR)
library(visdat)
library(lubridate)
library(see)
library(data.table)
library(gridExtra)
library(kableExtra)
opts_chunk$set(tidy = F)
```


# Introduction
\vspace{-4mm}

The data for this project ceom from the Multicenter AIDS Cohort Study which is a prospective and observational cohort of  homosexual and bisexual men with Human Immunodeficiency Virus (HIV-1). A primary goal of this study was to determine the effects of a common treatment - Highly Active Antiretroviral Treatment (HART). 
For this analysis, the main interest is to investigate how treatment response 2 years after being on HART differs between patients who report to be hard drug users at baseline vs. those who do not report hard drug use at baseline. 

The purpose of this report is to develop the analysis plann to answer the following hypotheses/questions of interest: 

Hypothesis 1: Non-hard drug users have a significantly lower viral load (HIV copies in a mL of blood) after 2 years of HART compared to hard-drug users. 

Hypothesis 2: Non-hard drug users have significantly higher CD4+ T cell count after 2 years of HART compared to hard-drug users.

Hypothesis 3: Aggregate mental quality of life significantly improve 2 years after HART among both hard-drug and non-hard drug users.

Hypothesis 4: Aggregate physical quality of life significantly improves 2 years after HART among both hard-drug and non-hard drug users. 

Hypothesis 5: 

\vspace{-8mm}
# Methods

\vspace{-8mm}
## Missingness
\vspace{-4mm}

Missingness will be investigated through summaries and visualization of missingness for each variable.
Relationships between missing data and all variables (outcomes and covariates) will be investigated. If data is not missing at random, we will conduct sensitivy analyses to determine how sensitive results are to different missing data assumptions. 

\vspace{-4mm}
## Data Cleaning
\vspace{-4mm}

Assessment of the four outcomes of interest did not reveal any abnormalities that needed to be addressed. We did observe that counts across the race categories and education at baseline categories were noticeably unbalanced. For this we...

\vspace{-6mm}
## Data Analysis
\vspace{-6mm}

We will conduct a multivariate general linear regression analysis between outcomes and five covariates of specific interest. The covaraites include, age, race, education, and smoking status at baseline. 
The assumptions of linearity, homoscedasticity, and normality will be assessed through diagnostic plots. 
A complete case analysis will be used for each model. 

We will investigate the hypotheses of interest through both a Frequentist and a Bayesian lens. 

### Frequentist Analyses

### Bayesian Analyses

\vspace{-6mm}
# Prelminary Results
\vspace{-6mm}

Meow meow 


