---
title: Project 2 Interim Data Analysis Plan
author: Diana Felipe
output: 
  bookdown::pdf_document2:
    toc: false
    number_sections: false
    latex_engine: xelatex
    extra_dependencies: ["longtable", "float"]
mainfont: Arial
fontsize: 12pt
documentclass: article
geometry: margin=1in
header-includes:
  - \usepackage{setspace}
  - \doublespacing
  - \usepackage{float}
  - \usepackage{caption}
  - \usepackage{titling}
  - \setlength{\droptitle}{-4cm}
  - \preauthor{\vspace{-0.6cm}}
  - \postauthor{\vspace{-3cm}}
---

```{r, echo = F, warning=F, message = F}
knitr::opts_chunk$set(echo = TRUE)


library(readr)
library(knitr)
library(ggplot2)
library(MASS)
library(emmeans)
library(multcomp)
library(kableExtra)
library(stats)
library(dplyr)
library(tibble)
library(labelled)
library(tableone)
library(lme4)
library(lmerTest)
library(nlme)
library(gtsummary)
library(gt)
library(ggeffects)
library(UpSetR)
library(visdat)
library(lubridate)
library(see)
library(data.table)
library(gridExtra)
library(kableExtra)
opts_chunk$set(tidy = F)
```

\vspace{-10mm}
# Introduction
\vspace{-10mm}

This investigation aims to uncover the association between cytokine & chemokine levels as well as amyloid deposition in both memory consolidation and AD-Signature corticol thickness. This study is one of the first to be done in humans as well as one of the first to assess changes over a one year period with aims of finding associations with clinical outcomes.
For Aim 1, we will be testing the hypothesis that higher baseline cytokine and chemokine levels as well as increases after 1 year can predict decreases in 
memory consolidation and AD-signature corticol thickness.
For Aim 2, we will test the hypothesis that the association of Amyloid Deposition with memory consolidation and AD-signature corticol thickness depends on the levels of cytokines/chemokines.

\vspace{-10mm}
# Methods
\vspace{-8mm}

For these analyses, we will use general linear regression models for each outcome of interest. 
For both Aim 1 and Aim 2, the primary outcomes of interest consists of the 5 memory consolidation variables as well as gray matter corticol thickness.
The primary explanatory variables (PEVs) of interest are the 4 chemokine/cytokine variables: IL-6, TNF-$\alpha$, MCD-1, and Eotaxin-1. 
We will adjust for age and sex in these models with additional covariates as necessary. 

For Aim 1a, we will use a general linear model for each of the 6 primary outcomes.
For each model, the outcome will be the value of the outcome at Year 1 and we will adjust for baseline values of the outcome as well as baseline values of the 4 chemokine/cytokine variables. 
<!-- Memory consolidation in this case is Long Term Consoidation I believe! -->
For Aim 1b, we will also use general linear regression where the outcome will be the change in the outcome from Year 1 to baseline. 
Covariates for this model will include the change from year 1 to baseline for each of the PEVs.  We will additionally include the baseline values of the PEVs. 
<!-- To allow for baseline differences. -->
For Aim 2, the model will be exactly as the model used for Aim 1b with the difference that we will additionally include an interaction between the change in Amyloid Deposition from Year 1 to baseline with the change in the chemokine/cytokine levels from Year 1 to baseline. 
We will additionally adjust for education, cardiovascular markers, 
<!-- (BMI, blood pressure, history of hypercholesterolemia),  -->
immune health history variables,
Clinical Dementia Rating, Geriartric Depression Scale, use of Non-Steroidal Anti-Inflammatory drugs, 
<!-- (recent infections and illnesses, surgical procedures in the past year, and auto-immune conditions),  -->
routinely collected cognitive measures,
<!-- (MoCA and neuropsychological assessment), -->
and APOE genotype as necessary.
Because the potential number of covariates is quite large, we will assess the relationships that the variables have with each other to determine if two variables are strongly correlated to reduce the number of covariates. 
<!-- Correlation matrix -->
We will check if any variables are associated with both the outcome and the primary explanatory variable, also known as a confounder.
Lastly, we will check if precision variables exist which are variables that are only associated with the outcome and not the PEV. 
With the remaining variables, we will conduct statistical tests to assess if a reduction of these variables results in a more simple and parsimonious model. 

\vspace{-10mm}
## Power Analysis
\vspace{-8mm}

We will conduct power analyses for both aims where we specify a significance level of $\alpha =$ 0.05.
Effect sizes for the power calculations will be based on the effect sizes from the preliminary studies. 
In regard to Aim 1, preliminary studies showed that higher baseline levels of IL-6 predicted decreases in gray matter ($\beta = -20.133$),
higher baseline levels of Eotaxin-1 predicted declines in episodic memory over 1 year ($\beta = -0.016$),
and increases in MCP-1 over 18-24 month predicted declines in memory ($\beta = -0.018$).
Additionally, higher levels of both Eotaxin-1 and MCP-1 were significantly associated with declines in memory and gray matter, although estimates were not given.
For Aim 2, effect sizes were not given for the interactions between amyloid deposition and peripheral inflammatory markers but elevated levels in both were significantly associated with declines in memory and gray matter.
We will conduct two separate power analyses for Aims 1 and 2 and we will create a tables of sufficient N to achieve different levels of power for effect sizes ranging from ~ -0.02 to ~ 20 which will allow us to determine power achievable with the planned sample size of 202.
We will use the mlrF.partial() function from the powertools package for all the power calculations. 


