---
title: Project 3 Data Analysis Plan
author: Diana Felipe
output: 
  bookdown::pdf_document2:
    toc: false
    number_sections: false
    latex_engine: xelatex
    extra_dependencies: ["longtable", "float"]
mainfont: Arial
fontsize: 12pt
geometry: margin=1in
header-includes:
  - \usepackage{setspace}
  - \doublespacing
  - \usepackage{float}
  - \usepackage{caption}
  - \usepackage{titling}
  - \usepackage{enumitem}
  - \setlength{\droptitle}{-4cm}
  - \preauthor{\vspace{-0.6cm}}
  - \postauthor{\vspace{-2.5cm}}
  - \setlist{nosep}
---

```{r, echo = F, warning=F, message = F}
knitr::opts_chunk$set(echo = TRUE)

library(tinytex)
library(readr)
library(knitr)
library(ggplot2)
library(kableExtra)
library(stats)
library(dplyr)
library(tibble)
library(labelled)
library(tableone)
library(gtsummary)
library(gt)
library(ggeffects)
library(UpSetR)
library(visdat)
library(lubridate)
library(see)
library(data.table)
library(gridExtra)
library(kableExtra)
library(readr)
library(here)
library(dplyr)
library(ggplot2)
library(naniar)
library(see)
library(pillar)
library(visdat)
library(finalfit)
library(table1)
library(here)

# Read in raw data
raw_data <- read_csv(here("Project3", "Data", "frmgham2.csv"))

# Read in modified data
surv_df <- read_csv(here("Project3", "Data", "pre_surv_df.csv"))

opts_chunk$set(tidy = F)
```


<!-- \vspace{-6mm} -->
# Introduction
<!-- \vspace{-6mm} -->

The data for this project come from the Framington Heart Study which is a longitudinal study with the primary goal of investigating the etiology of cardiovascular disease. The study was conducted on an initial population of 5,209 individuals residing in Framingham, Massachusetts on which data was collected for blood pressure, health behaviors, medication use, and more.
The purpose of this report is to develop the analysis plan to investigate the research questions of interest. 
The primary goal of the analysis is to identify risk factors of stroke within a 10-year period for five different risk profiles.

\vspace{-10mm}
# Methods
\vspace{-7mm}
## Data Cleaning
\vspace{-6mm}
The original raw data contained 11627 observations for 4,434 subjects and 38 original covariates. Missingness was assessed in this data set through summaries and visualizations. Regarding the primary variables of interest, BP Meds had ~5% missingness (593 obs.), Total cholesterol had 3.5% missingness, and BMI had ~0.5% missingness. We did observe observe high rates for High and Low Density Lipoprotein cholesterol with ~74% missingness. We verified that there were no relationships between missingness and all variables and therefore concluded that data was Missing At Random. 

We then proceeded with creating new variables specifically for the 10 year window of interest for the primary analysis. 
We created an indicator variable for whether subjects had a stroke within 10 years (Yes/No) -  \textit{STROKE10} as well as the time to stroke -\textit{STROKE10TIME}.
We accounted for subjects that died within 10 years or had a stroke at baseline visit. 

\vspace{-8mm}
## Data Analysis
\vspace{-6mm}
We will conduct analyses separately for sex and females. 
For the primary analysis, we will fit a Cox Proportional Hazards (PH) Model to investigate the association baseline covariates and time to stroke for the five risk profiles of interest: 

\vspace{-3mm}
\begin{itemize}
  \item Subjects with no risk factors for the average person
  \item Subjects with high blood pressure (BP $>160$)
  \item Subjects with diabetes
  \item Subjects with both high blood pressure and diabetes
  \item Subjects who are smokers
\end{itemize}
\vspace{-3mm}

Potential covariates include Presence of Coronary Heart Disease (CHD), whether subjects were on Blood Pressure (BP) medications, smoking status, total Cholesterol, and Body Mass Index (BMI). 
We will perform variable selection with Least Absolute Shrinkage Selection Operator (LASSO) to identify the variables that are most meaningful and relevant for time to stroke. We will specifically use the glmnet R package for this. 
We will follow this by assessing the relationships between the variables with each other and the outcomes to identify potential confounders or precision variables. 
We will include the same set of variables for each sex-stratified analysis.
We will adjust for Age, Diabetes status, and log transformed Systolic Blood Pressure (BP) in all analyses. 
As Diabetes status and BP are not constant and change for each visit, we will provide a description of how these variables are changing over time to determine if a time varying analysis is more appropriate for future analyses. 
We will assess whether the proportional hazards assumptions for the model through the Schoenfeld Residuals Test as well visually through Log Minus Log (LML) survival plots for each covariate included in the final model. 

In the final report, we will report hazard ratios for the covariates, p-values, and confidence intervals. We will use a significance level of $\alpha = 0.05$.
A Table 1 as well as tables and figures describing the data and analysis results will be included. 
All analyses will be conducted with R version 4.4.1 using the glmnet, survival, survminer packages. 

<!-- These analyses will allow us to identify risk factors that predict stroke in a 10 year span for the five risk profiles of interest.  -->

